dist: trusty
sudo: required
language: c

git:
  depth: 1

notifications:
  email: false

services:
  - docker

env:
  global:
    - HTTPBIN_HOST=127.0.0.1

before_script:
  - make
  - docker run -d -p 80:80 kennethreitz/httpbin

script:
  - make test
