dist: trusty
sudo: false
language: c

git:
  depth: 1

notifications:
  email: false

services:
  - docker

env:
  global:
    - HTTPBIN_HOST=httpbin.org

before_script:
  - make

script:
  - make test
